project_id = "ukrgzsntvddzwtmccwbf"

[functions.invite-user]
verify_jwt = false

[functions.sla-monitor]
verify_jwt = false

[functions.machine-secrets]
verify_jwt = true

[functions.manage-user]
verify_jwt = true

[functions.send-comment-notification]
verify_jwt = false

[functions.receive-email-reply]
verify_jwt = false
