project_id = "ukrgzsntvddzwtmccwbf"

[functions.invite-user]
verify_jwt = false

[functions.sla-monitor]
verify_jwt = false

[functions.acknowledge-sla]
verify_jwt = false

[functions.machine-secrets]
verify_jwt = true

[functions.manage-user]
verify_jwt = false

[functions.send-comment-notification]
verify_jwt = false

[functions.receive-email-reply]
verify_jwt = false

[functions.send-analyst-notification]
verify_jwt = false

[functions.send-monthly-report]
verify_jwt = false

[functions.send-resolution-notification]
verify_jwt = false

[functions.submit-feedback]
verify_jwt = false

[functions.unlock-inactive-tickets]
verify_jwt = false

[functions.send-rfc-decision-notification]
verify_jwt = false

[functions.fetch-holidays]
verify_jwt = false

[functions.send-rfc-report]
verify_jwt = false
