// This file is automatically generated. Do not edit it directly.
// EXCEÇÃO INTENCIONAL: as duas constantes abaixo foram trocadas de
// valores hardcoded (project ref antigo/errado) para lerem do .env.
// Se este arquivo for regenerado pelo fluxo automático (Lovable/Supabase),
// essa mudança será sobrescrita — reaplicar a leitura via import.meta.env
// nesse caso.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});