// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukrgzsntvddzwtmccwbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcmd6c250dmRkend0bWNjd2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MTkxNDEsImV4cCI6MjA3ODA5NTE0MX0.gVTZbSuU2cIYjjpqtAwMlGHm4P-p8z4AlnH2z4dz62A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});