name: Deploy Manual para Vercel

# O comando workflow_dispatch é o que cria o botão de acionamento manual no GitHub
on:
  workflow_dispatch: 

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Producao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v6

      - name: Configurar Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'          # Cacheia node_modules entre execuções, acelera o build

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Puxar configurações da Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Construir o projeto (Build)
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Fazer o Deploy
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
